language: node_js
matrix:
  fast_finish: true
  include:
    - os: osx
      node_js: 6
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
      node_js: 6
cache:
  yarn: true
  directories:
  - node_modules
addons:
  apt:
    packages:
      - rpm
      - bsdtar
      - libavahi-compat-libdnssd-dev
script:
- yarn run lint
- yarn run dist
- ls dist
deploy:
  provider: script
  script: publish-website.sh
  on:
    tags: true
    branch: master
