# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

os: Visual Studio 2015

# Test against this version of Node.js
environment:
  nodejs_version: "6"
  BONJOUR_SDK_HOME: "C:\\Program Files\\Bonjour SDK"

platform: x64

init:
  - git config --global core.autocrlf input

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # Install Bonjour for msdn
  # https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/appveyor.yml
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  # install modules
  - yarn

build_script:
  - yarn run lint
  - yarn run dist

test: off

artifacts:
  - path: dist/*.exe
    name: NSIS Installer
  - path: dist/latest.yml
    name: YML for Squirrel

deploy:
  provider: GitHub
  artifact: /(.*\.)(exe|yml)/
  auth_token:
    secure: TOPUgyRafIA8Q304QB7iwALoHPE445Ni8JjR5TOVrEoxInGSzF164y9Vp8+o82/o # your encrypted token from GitHub
  on:
    appveyor_repo_tag: true        # deploy on tag push only
